library ieee;
use ieee.std_logic_1164.all;

entity GENPROP_0 is
 port(A, B,C_in: in std_logic;
      gnrat: out std_logic);
end GENPROP_0;

-- this is the very first block in the sparse tree, i.e. the block in the row 0 and column 0. It receives as inputs, in addition to A and B, the carry in.
-- this block has only one output, a "generate", while the propagate function is not computed, cause the carry could be only generated by this block, not propagated

 architecture BEHAVIORAL of GENPROP_0 is
    
	
     
 begin
	
	 gnrat <= ((A AND B) OR ((A XOR B) AND C_in));
	 
	-- prpgat <= '0';
	 
	 
 end BEHAVIORAL;	 