library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.numeric_std.all;

entity CARRY_SELECT_BLOCK is
	generic (N: integer:= 32);
	port(A,B: in std_logic_vector(N-1 downto 0); -- the inputs A and B of the carry select block are also inputs of the entity of the overall Pentium 4 
		 Cin: in std_logic; -- Cin takes in input the i-th carry generated by the carry generator structure (sparse tree)
		 --Cout: out std_logic;
         Sum:  out std_logic_vector(N-1 downto 0));
end CARRY_SELECT_BLOCK;

architecture STRUCTURAL of CARRY_SELECT_BLOCK is -- structural description: used RCA and MUX21 blocks and connected them

signal out_RCA_1,out_RCA_2: std_logic_vector(N-1 downto 0);
signal Co_tmp1,Co_tmp2:std_logic;

component RCA_GEN 
	generic (NBIT: integer:= 32);
	Port (A:	In	std_logic_vector(NBIT-1 downto 0);
			B:	In	std_logic_vector(NBIT-1 downto 0);
			Ci:	In	std_logic;
			S:	Out	std_logic_vector(NBIT-1 downto 0);
			Co:	Out	std_logic);
end component;

component MUX21_GENERIC 
	Generic (NBIT: integer:= 32);
	Port (A_mux:	In	std_logic_vector(NBIT-1 downto 0) ;
			B_mux:	In	std_logic_vector(NBIT-1 downto 0);
			SEL_mux:	In	std_logic;
			Y_mux:	Out	std_logic_vector(NBIT-1 downto 0));
end component;

begin

-- here we have two different RCAs: one has an input carry set to 1, while the other has an input carry set to '0'. They both receive in input the same 4 bits of A and B and compute the sum taking into account their own carry in. Then, the multiplexer selects which sum "has to be taken", based on one of the carry received by the carry generator.
-- The Cou is not used, thus is connected to a dummy signal
	RCA_1: RCA_GEN generic map(NBIT=>N) port map(A=>A,B=>B,Ci=>'0',Co=>Co_tmp1,S=>out_RCA_1);
	RCA_2: RCA_GEN generic map(NBIT=>N) port map(A=>A,B=>B,Ci=>'1',Co=>Co_tmp2,S=>out_RCA_2);
	MUX_1: MUX21_GENERIC generic map(NBIT=>N) port map(A_mux=>out_RCA_2,B_mux=>out_RCA_1,SEL_mux=>Cin,Y_mux=>Sum);

end STRUCTURAL;