library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use ieee.numeric_std.all;

-- the sum generator is the structure that connects all the carry select blocks, and receives as inputs, in addition to the two operands A and B, the carries in generated by the carry generator structure

entity SUM_GENERATOR is
	generic(NBIT: integer:=32;M: integer:=4);
	port(A,B: in std_logic_vector(NBIT-1 downto 0);
		  Cin: in std_logic_vector((NBIT/4)-1 downto 0); -- e.g.: Cin are 8 if the sum generator has 32 bits, 4 if the the sum generator has 16 bits, and so on
        Sum:  out std_logic_vector(NBIT-1 downto 0));
--Cout not used
end SUM_GENERATOR; 

architecture STRUCTURAL of SUM_GENERATOR is

	component CARRY_SELECT_BLOCK 
		generic (N: integer:= 32);
		port(A,B: in std_logic_vector(N-1 downto 0);
		  Cin: in std_logic;
        Sum:  out std_logic_vector(N-1 downto 0));
	end component;

	begin

	CARRY_BLOCK_GEN:for i in 0 to ((NBIT/4)-1) generate
--in order to generalize the structure dimension, i.e. to allow to use this sum generator with 16, 32, 64 bits inputs, we divided the description of the variuos blocks in two "parts": the first part describes the first carry select block, which receives as inputs the first of the N/4th carries, while the second describes in a generic way (based on indexes), all the remaining blocks  
      block0: if (i = 0) generate	
		CARRY_BLOCK_0: CARRY_SELECT_BLOCK generic map(N=>M) port map(A=>A(M-1 downto 0),B=>B(M-1 downto 0),Cin=>Cin(0),Sum=>Sum(M-1 downto 0));
	  end generate block0;	
		CARRY_BLOCK_i: CARRY_SELECT_BLOCK generic map(N=>M) port map(A=>A(((4*i)+(M-1)) downto (4*i)),B=>B(((4*i)+(M-1)) downto (4*i)),Cin=>Cin(i),Sum=>Sum(((4*i)+(M-1)) downto (4*i)));
	end generate;

end STRUCTURAL;